FROM python:3.13

WORKDIR /app

COPY . .

RUN pip install fastapi sqlalchemy pydantic uvicorn pwdlib requests argon2-cffi PyJWT psycopg2-binary python-multipart python-dotenv psycopg

CMD ["uvicorn","mainer:app","--host","0.0.0.0","--port","8000"]